# Generated by Django 3.2.9 on 2021-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0010_auto_20211112_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smartphone',
            },
        ),
        migrations.AlterModelTable(
            name='laptops',
            table='laptops',
        ),
        migrations.AlterModelTable(
            name='sellermodel',
            table='seller',
        ),
    ]
