# Generated by Django 3.2.9 on 2021-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0011_auto_20211117_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
