# Generated by Django 3.2.9 on 2021-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0011_auto_20211114_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name': 'smartphone', 'verbose_name_plural': 'smartphones'},
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='media/smartphones'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='sellermodel',
            table='seller',
        ),
        migrations.AlterModelTable(
            name='smartphone',
            table=None,
        ),
    ]
