# Generated by Django 3.2.9 on 2021-11-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techeria_app', '0012_auto_20211117_0657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
