name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: f1234
        ports:
        - 3306:3306
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ProjectTecheria
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG:  ${{ secrets.DEBUG }}
        DB_USER: root
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST:  ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}




      run: |
        cd ./techeria_controller
        python manage.py test
