name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Open ProjectTecheria
      run: |
        cd ./techeria_controller

    - name: Coverage report
      run: |
        pip install coverage
        cd ./techeria_controller
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        cd ./techeria_controller
        python3 manage.py test
