name: Tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          DB_DATABASE: techeria_db
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: f1234
        ports:
          - 3306


    steps:
      - uses: actions/checkout@v1

    
