name: Tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          DB_DATABASE: techeria_db
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: f1234
        ports:
          - 3306


    steps:
      - uses: actions/checkout@v1

      # - name: Verify MySQL connection
      #   run: |
      #     mysql --version
      #     sudo apt-get install -y mysql-client
      #     mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uuser -psecret -e "SHOW DATABASES"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        run: |
          php --version
          composer config "http-basic.nova.laravel.com" "${{ secrets.DB_USER }}" "${{ secrets.DB_PASSWORD }}"
          composer install -n --prefer-dist


      - name: Run tests
        run: ./vendor/bin/phpunit -v
        env:
            DB_PORT: ${{ job.services.mysql.ports['3306'] }}
